# Generated by Django 3.0.2 on 2020-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
